### ISSUE TITLE
If the light sensor gets momentarily covered and uncovered, the landing module shouldn't think it's in the rocket

### ISSUE THREAD

**Issue by iansan5653** [KyleHunter/SOAR_NSL_CV#2]
If, for example, we insert the landing module and then have to remove the parachute for whatever reason, the lander will act like it's out of the rocket from then on -- it won't do anything because altitude < 10, but once the rocket takes off it will fuck up.

Instead of waiting until no light is sensed, why don't we wait until a wireless SSH command is received and *then* start checking for light to be sensed? Then I won't send the command until we're definitely ready. The buzzer should still activate whenever no light is sensed and altitude < 10 though.

**Comment by KyleHunter** [comment]
Too sketchy to have to rely on having wifi with the pi I feel. Especially since we never got the new wifi usb to actually work with it
